const express = require('express');
const fs = require('fs');
const path = require('path');
const { getDatabase } = require('../database');
const { authenticateToken } = require('../middleware/auth');

const router = express.Router();

// Helper function to generate HTML report
const generateHTMLReport = (data) => {
  const { summary, motionEvents, recordings, cameras, period } = data;
  
  return `
<!DOCTYPE html>
<html>
<head>
    <title>Guarddog Daily Summary Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary { background: #f5f5f5; padding: 20px; border-radius: 5px; margin: 20px 0; }
        .section { margin: 30px 0; }
        .chart { margin: 20px 0; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .alert { color: #d32f2f; font-weight: bold; }
        .success { color: #388e3c; font-weight: bold; }
        .footer { margin-top: 50px; text-align: center; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Guarddog Surveillance Report</h1>
        <h2>${new Date().toLocaleDateString()}</h2>
        <p>Period: ${period}</p>
    </div>
    
    <div class="summary">
        <h3>Summary</h3>
        <p><strong>Total Motion Events:</strong> ${summary.totalMotionEvents}</p>
        <p><strong>People Detected:</strong> ${summary.totalPeople}</p>
        <p><strong>Pets Detected:</strong> ${summary.totalPets}</p>
        <p><strong>Vehicles Detected:</strong> ${summary.totalVehicles}</p>
        <p><strong>Recordings Created:</strong> ${summary.totalRecordings}</p>
        <p><strong>Storage Used:</strong> ${(summary.totalStorageUsed / (1024 * 1024)).toFixed(2)} MB</p>
    </div>
    
    <div class="section">
        <h3>Camera Status</h3>
        <table>
            <tr>
                <th>Camera Name</th>
                <th>Type</th>
                <th>Status</th>
                <th>Motion Events</th>
                <th>Recordings</th>
            </tr>
            ${cameras.map(camera => `
            <tr>
                <td>${camera.name}</td>
                <td>${camera.type}</td>
                <td class="${camera.is_active ? 'success' : 'alert'}">${camera.is_active ? 'Active' : 'Inactive'}</td>
                <td>${camera.motion_count || 0}</td>
                <td>${camera.recording_count || 0}</td>
            </tr>
            `).join('')}
        </table>
    </div>
    
    <div class="section">
        <h3>Recent Motion Events</h3>
        <table>
            <tr>
                <th>Time</th>
                <th>Camera</th>
                <th>Event Type</th>
                <th>Confidence</th>
            </tr>
            ${motionEvents.slice(0, 20).map(event => `
            <tr>
                <td>${new Date(event.timestamp).toLocaleString()}</td>
                <td>${event.camera_name}</td>
                <td>${event.event_type}</td>
                <td>${Math.round(event.confidence * 100)}%</td>
            </tr>
            `).join('')}
        </table>
    </div>
    
    <div class="section">
        <h3>Recordings</h3>
        <table>
            <tr>
                <th>Time</th>
                <th>Camera</th>
                <th>Duration</th>
                <th>Size</th>
                <th>Motion Detected</th>
            </tr>
            ${recordings.slice(0, 20).map(recording => `
            <tr>
                <td>${new Date(recording.created_at).toLocaleString()}</td>
                <td>${recording.camera_name}</td>
                <td>${recording.duration ? Math.round(recording.duration) + 's' : 'N/A'}</td>
                <td>${recording.file_size ? (recording.file_size / (1024 * 1024)).toFixed(2) + ' MB' : 'N/A'}</td>
                <td class="${recording.motion_detected ? 'alert' : ''}">${recording.motion_detected ? 'Yes' : 'No'}</td>
            </tr>
            `).join('')}
        </table>
    </div>
    
    <div class="footer">
        <p>Generated by Guarddog Surveillance System</p>
        <p>${new Date().toISOString()}</p>
    </div>
</body>
</html>
  `;
};

// Helper function to generate CSV data
const generateCSVData = (data) => {
  const { motionEvents, recordings } = data;
  
  let csv = 'Type,Timestamp,Camera,Event Type,Confidence,Duration,File Size,Motion Detected\n';
  
  motionEvents.forEach(event => {
    csv += `Motion Event,${event.timestamp},${event.camera_name},${event.event_type},${event.confidence},,${event.motion_detected ? 'Yes' : 'No'}\n`;
  });
  
  recordings.forEach(recording => {
    csv += `Recording,${recording.created_at},${recording.camera_name},,${recording.duration || ''},${recording.file_size || ''},${recording.motion_detected ? 'Yes' : 'No'}\n`;
  });
  
  return csv;
};

// Generate daily summary report
router.get('/daily-summary', authenticateToken, async (req, res) => {
  const { date, format = 'html' } = req.query;
  const db = getDatabase();
  
  try {
    // Use provided date or today
    const reportDate = date ? new Date(date) : new Date();
    const startDate = new Date(reportDate);
    startDate.setHours(0, 0, 0, 0);
    const endDate = new Date(reportDate);
    endDate.setHours(23, 59, 59, 999);
    
    // Get motion events for the day
    const motionEvents = await new Promise((resolve, reject) => {
      db.all(
        `SELECT me.*, c.name as camera_name 
         FROM motion_events me 
         JOIN cameras c ON me.camera_id = c.id 
         WHERE me.timestamp BETWEEN ? AND ? 
         ORDER BY me.timestamp DESC`,
        [startDate.toISOString(), endDate.toISOString()],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Get recordings for the day
    const recordings = await new Promise((resolve, reject) => {
      db.all(
        `SELECT r.*, c.name as camera_name 
         FROM recordings r 
         JOIN cameras c ON r.camera_id = c.id 
         WHERE r.created_at BETWEEN ? AND ? 
         ORDER BY r.created_at DESC`,
        [startDate.toISOString(), endDate.toISOString()],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Get camera information with counts
    const cameras = await new Promise((resolve, reject) => {
      db.all(
        `SELECT 
           c.*,
           COUNT(DISTINCT me.id) as motion_count,
           COUNT(DISTINCT r.id) as recording_count
         FROM cameras c
         LEFT JOIN motion_events me ON c.id = me.camera_id 
           AND me.timestamp BETWEEN ? AND ?
         LEFT JOIN recordings r ON c.id = r.camera_id 
           AND r.created_at BETWEEN ? AND ?
         GROUP BY c.id`,
        [startDate.toISOString(), endDate.toISOString(), startDate.toISOString(), endDate.toISOString()],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Calculate summary statistics
    const summary = {
      totalMotionEvents: motionEvents.length,
      totalPeople: motionEvents.filter(e => e.event_type === 'person').length,
      totalPets: motionEvents.filter(e => e.event_type === 'pet').length,
      totalVehicles: motionEvents.filter(e => e.event_type === 'vehicle').length,
      totalRecordings: recordings.length,
      totalStorageUsed: recordings.reduce((sum, r) => sum + (r.file_size || 0), 0)
    };
    
    const reportData = {
      summary,
      motionEvents,
      recordings,
      cameras,
      period: `${startDate.toLocaleDateString()} - ${endDate.toLocaleDateString()}`,
      generatedAt: new Date().toISOString()
    };
    
    if (format === 'json') {
      res.json(reportData);
    } else if (format === 'csv') {
      const csvData = generateCSVData(reportData);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="guarddog-report-${reportDate.toISOString().split('T')[0]}.csv"`);
      res.send(csvData);
    } else {
      // Default to HTML
      const htmlReport = generateHTMLReport(reportData);
      res.setHeader('Content-Type', 'text/html');
      res.send(htmlReport);
    }
    
  } catch (error) {
    console.error('Report generation error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// Generate custom period report
router.get('/custom', authenticateToken, async (req, res) => {
  const { startDate, endDate, format = 'html', cameras: cameraIds } = req.query;
  const db = getDatabase();
  
  if (!startDate || !endDate) {
    return res.status(400).json({ error: 'Start date and end date are required' });
  }
  
  try {
    const start = new Date(startDate);
    const end = new Date(endDate);
    
    // Build camera filter
    let cameraFilter = '';
    let cameraParams = [];
    if (cameraIds) {
      const ids = Array.isArray(cameraIds) ? cameraIds : [cameraIds];
      cameraFilter = ` AND c.id IN (${ids.map(() => '?').join(',')})`;
      cameraParams = ids;
    }
    
    // Get motion events for the period
    const motionEvents = await new Promise((resolve, reject) => {
      db.all(
        `SELECT me.*, c.name as camera_name 
         FROM motion_events me 
         JOIN cameras c ON me.camera_id = c.id 
         WHERE me.timestamp BETWEEN ? AND ?${cameraFilter}
         ORDER BY me.timestamp DESC`,
        [start.toISOString(), end.toISOString(), ...cameraParams],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Get recordings for the period
    const recordings = await new Promise((resolve, reject) => {
      db.all(
        `SELECT r.*, c.name as camera_name 
         FROM recordings r 
         JOIN cameras c ON r.camera_id = c.id 
         WHERE r.created_at BETWEEN ? AND ?${cameraFilter}
         ORDER BY r.created_at DESC`,
        [start.toISOString(), end.toISOString(), ...cameraParams],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Get camera information
    const cameras = await new Promise((resolve, reject) => {
      const cameraQuery = cameraIds ? 
        `SELECT * FROM cameras WHERE id IN (${cameraIds.map(() => '?').join(',')})` :
        `SELECT * FROM cameras`;
      
      db.all(cameraQuery, cameraParams, (err, rows) => {
        if (err) reject(err);
        else resolve(rows || []);
      });
    });
    
    // Calculate summary
    const summary = {
      totalMotionEvents: motionEvents.length,
      totalPeople: motionEvents.filter(e => e.event_type === 'person').length,
      totalPets: motionEvents.filter(e => e.event_type === 'pet').length,
      totalVehicles: motionEvents.filter(e => e.event_type === 'vehicle').length,
      totalRecordings: recordings.length,
      totalStorageUsed: recordings.reduce((sum, r) => sum + (r.file_size || 0), 0)
    };
    
    const reportData = {
      summary,
      motionEvents,
      recordings,
      cameras,
      period: `${start.toLocaleDateString()} - ${end.toLocaleDateString()}`,
      generatedAt: new Date().toISOString()
    };
    
    if (format === 'json') {
      res.json(reportData);
    } else if (format === 'csv') {
      const csvData = generateCSVData(reportData);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="guarddog-custom-report.csv"`);
      res.send(csvData);
    } else {
      const htmlReport = generateHTMLReport(reportData);
      res.setHeader('Content-Type', 'text/html');
      res.send(htmlReport);
    }
    
  } catch (error) {
    console.error('Custom report generation error:', error);
    res.status(500).json({ error: 'Failed to generate custom report' });
  }
});

// Get report statistics
router.get('/stats', authenticateToken, (req, res) => {
  const db = getDatabase();
  const { period = '30d' } = req.query;
  
  // Calculate date range
  const now = new Date();
  let startDate;
  
  switch (period) {
    case '7d':
      startDate = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
      break;
    case '30d':
      startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
      break;
    case '90d':
      startDate = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
      break;
    default:
      startDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  }
  
  // Get daily motion event counts
  db.all(
    `SELECT 
       DATE(timestamp) as date,
       event_type,
       COUNT(*) as count
     FROM motion_events 
     WHERE timestamp >= ?
     GROUP BY DATE(timestamp), event_type
     ORDER BY date DESC`,
    [startDate.toISOString()],
    (err, dailyStats) => {
      if (err) {
        return res.status(500).json({ error: 'Database error' });
      }
      
      // Get daily recording counts
      db.all(
        `SELECT 
           DATE(created_at) as date,
           COUNT(*) as count,
           SUM(file_size) as total_size
         FROM recordings 
         WHERE created_at >= ?
         GROUP BY DATE(created_at)
         ORDER BY date DESC`,
        [startDate.toISOString()],
        (err, recordingStats) => {
          if (err) {
            return res.status(500).json({ error: 'Database error' });
          }
          
          res.json({
            dailyMotionStats: dailyStats,
            dailyRecordingStats: recordingStats,
            period,
            startDate: startDate.toISOString(),
            endDate: now.toISOString()
          });
        }
      );
    }
  );
});

// Export report data as JSON for external processing
router.get('/export', authenticateToken, async (req, res) => {
  const { startDate, endDate, includeRecordings = 'false' } = req.query;
  const db = getDatabase();
  
  if (!startDate || !endDate) {
    return res.status(400).json({ error: 'Start date and end date are required' });
  }
  
  try {
    const start = new Date(startDate);
    const end = new Date(endDate);
    
    const exportData = {
      exportInfo: {
        startDate: start.toISOString(),
        endDate: end.toISOString(),
        generatedAt: new Date().toISOString(),
        version: '1.0.0'
      }
    };
    
    // Get cameras
    exportData.cameras = await new Promise((resolve, reject) => {
      db.all('SELECT * FROM cameras', (err, rows) => {
        if (err) reject(err);
        else resolve(rows || []);
      });
    });
    
    // Get motion events
    exportData.motionEvents = await new Promise((resolve, reject) => {
      db.all(
        `SELECT me.*, c.name as camera_name 
         FROM motion_events me 
         JOIN cameras c ON me.camera_id = c.id 
         WHERE me.timestamp BETWEEN ? AND ?`,
        [start.toISOString(), end.toISOString()],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    // Get recordings metadata (optionally include file paths)
    const recordingFields = includeRecordings === 'true' 
      ? 'r.*, c.name as camera_name'
      : 'r.id, r.camera_id, r.filename, r.file_size, r.duration, r.motion_detected, r.ai_objects, r.created_at, c.name as camera_name';
    
    exportData.recordings = await new Promise((resolve, reject) => {
      db.all(
        `SELECT ${recordingFields}
         FROM recordings r 
         JOIN cameras c ON r.camera_id = c.id 
         WHERE r.created_at BETWEEN ? AND ?`,
        [start.toISOString(), end.toISOString()],
        (err, rows) => {
          if (err) reject(err);
          else resolve(rows || []);
        }
      );
    });
    
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Content-Disposition', 'attachment; filename="guarddog-export.json"');
    res.json(exportData);
    
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Failed to export data' });
  }
});

module.exports = router;